version: '3.8'

services:
  auth-service:
    image: auth-service:latest
    container_name: auth-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tripply
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Tripply@123
    networks:
      - tripply-network

networks:
  tripply-network:
    external: true
