server:
  port: 8082
  servlet:
    context-path: /auth

spring:
  application:
    name: auth
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: postgres
    password: Tripply@123
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

application:
  notification:
    base-url: http://NOTIFICATION
  booking:
    base-url: http://BOOKING

eureka:
  client:
    service-url:
      defaultZone: http://tripply-registery-container:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: tripply-registery-container

#swagger-url: http://localhost:8082/auth/swagger-ui/index.html