server:
  port: 8082
  servlet:
    context-path: /auth

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tripply
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

application:
  notification:
    base-url: http://localhost:8087
  booking:
    base-url: http://localhost:8085

#swagger-url: http://localhost:8082/auth/swagger-ui/index.html