server:
  port: 8082
  servlet:
    context-path: /auth

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tripply?currentSchema=identity
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

application:
  notification:
    base-url: http://localhost:8087
  booking:
    base-url: http://localhost:8085




