server:
  port: 8082
  servlet:
    context-path: /auth


spring:
  application:
    name: auth
    version: 1.0
  datasource:
    url: jdbc:postgresql://localhost:5433/tripply
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

application:
  notification:
    base-url: http://NOTIFICATION
  booking:
    base-url: http://BOOKING
  auth:
    base-url: http://AUTH
  ui:
    base-url: http://localhost:3000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

swagger-url: http://localhost:8082/auth/swagger-ui/index.html